### ISSUE TITLE
Read Field Data

### ISSUE THREAD

**Issue by andresegido** [JuliaVTK/ReadVTK.jl#41]
Hello! I just started playing around with ReadVTK. Thank you very much for the effort!

Reading some cases I have, I did not find any way to read Field Data from vtk files. Passing very quickly through the documentation and the source code I found that there is already an implemented type for this (VTKBase.VTKFieldData) but there is no function to read this data from a file (in the manner of get_cells_data() or get_points_data()).

Is there any chance you will be implementing this functionality soon? Thanks in advance!

**Comment by ranocha** [comment]
Thanks for your interest! I guess none of the contributors so far have a need for this, so we will likely not implement it in the near future. But if you need it and want to give it a shot, we may be able to assist you and review your PR.

**Comment by andresegido** [comment]
Just did that! Let me know if/when you incorporate the changes.
Just out of curiosity: you're not considering implementing multiblock or Paraview collections in the near future, right?

**Comment by ranocha** [comment]
> Just did that! Let me know if/when you incorporate the changes. 

Thanks! @sloede and/or I will have a look at it (when we have time)

> Just out of curiosity: you're not considering implementing multiblock or Paraview collections in the near future, right?

Same as with every other feature - this is an open source project, so we're happy to welcome contributions but we will likely not work on it unless we need it ourselves 🙂
